[package]
name = "lunar"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"
default-run = "lunar"
authors = [
  "Patrick Hilhorst"
]

[features]
default = ["asm"]
# Enables custom assembly. Can be disabled on platforms that support it
# to test "generic" code. All ASM _should_ be feature-gated.
asm = []
# Explicitly uses std::simd. Currently experimental, so disabled by default
simd = []

[profile.release]
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1

# Make the build script run faster.
[profile.dev]
opt-level = 3

[dependencies]
strum = "0.24"
strum_macros = "0.24"
crossbeam-channel = "0.5"
smallvec = "1.10"
static_assertions = "1.1"
no-panic = "0.1"
textwrap = "0.16"

[build-dependencies]
rand = { version = "0.8", features = ["small_rng"], default-features = false }
yaml-rust = "0.4"

[dev-dependencies]
csv = "1.1"
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "perft_bench"
harness = false
