[package]
name = "lunar"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"
default-run = "lunar"
authors = [
  "Patrick Hilhorst"
]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
codegen-units = 1

# Make the build script run faster.
[profile.dev]
opt-level = 3

[dependencies]
strum = "0.24"
strum_macros = "0.24"
crossbeam-channel = "0.5"
smallvec = "1.10"

[dependencies.rand]
version = "0.8"
features = ["small_rng"]
default-features = false

[build-dependencies.rand]
version = "0.8"
features = ["small_rng"]
default-features = false

[dev-dependencies.criterion]
version = "0.4"
features = ["html_reports"]

[[bench]]
name = "perft_bench"
harness = false
