on:
  workflow_dispatch:

jobs:
  datagen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup
      run: |
        cargo install cargo-pgo
        rustup component add llvm-tools-preview

        pushd ..
        git clone https://github.com/jw1912/bullet
        cd bullet
        git checkout "main@{2025-07-02}"
        cargo build --release --bin bullet-utils
        popd
    - name: Datagen
      run: |
        ./scripts/datagen.sh
        ls data
    - name: Exfiltrate data
      env:
        CROC_SECRET: 'lunar-${{ secrets.CROC_TOKEN_PART }}'
      run: |
        nix \
          --extra-experimental-features flakes \
          --extra-experimental-features nix-command \
          run nixpkgs#croc -- \
          send data
