on:
  workflow_dispatch:

jobs:
  datagen:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        a: [0, 1, 2, 3, 4, 5, 6, 7]
        b: [0, 1, 2, 3, 4, 5, 6, 7]
        c: [0, 1, 2, 3]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup
      run: |
        cargo install cargo-pgo
        rustup component add llvm-tools-preview

        pushd ..
        git clone https://github.com/jw1912/bullet
        cd bullet
        git checkout "main@{2025-07-02}"
        cargo build --release --bin bullet-utils
        popd
    - name: Datagen
      env:
        CROC_SECRET: 'lunar-${{ secrets.CROC_TOKEN_PART }}'
      run: |
        ./scripts/datagen.sh
        ls -la data
        nix \
          --extra-experimental-features flakes \
          --extra-experimental-features nix-command \
          shell nixpkgs#croc --command sh -c 'cat data/*.bin | croc send'
