on:
  workflow_dispatch:

jobs:
  datagen:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        a: [0, 1, 2, 3, 4, 5, 6, 7]
        b: [0, 1, 2, 3, 4, 5, 6, 7]
        c: [0, 1, 2, 3]
    steps:
    - uses: actions/checkout@v3
      with:
          lfs: true
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup
      run: |
        cargo install cargo-pgo
        rustup component add llvm-tools-preview

        pushd ..
        git clone https://github.com/jw1912/bullet
        cd bullet
        git checkout "main@{2025-07-02}"
        cargo build --release --bin bullet-utils
        popd
    - name: Datagen
      env:
        CROC_SECRET: 'lunar-${{ secrets.CROC_TOKEN_PART }}-${{ matrix.a }}-${{ matrix.b }}-${{ matrix.c }}'
      run: |
        ./scripts/datagen.sh
        mv data/*.bin data/$(date +%s).bin
        ls -lh data
    - uses: actions/upload-artifact@v4
      with:
        name: generated-${{matrix.a}}-${{matrix.b}}-${{matrix.c}}.bin
        path: data/*.bin
        retention-days: 2
        compression-level: 9
        include-hidden-files: true
