on:
  workflow_dispatch:

jobs:
  datagen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup
      run: |
        cargo install cargo-pgo
        rustup component add llvm-tools-preview

        pushd ..
        git clone https://github.com/jw1912/bullet
        cd bullet
        git checkout "main@{2025-07-02}"
        cargo build --release --bin bullet-utils
        popd
    - name: Datagen
      run: |
        ./scripts/datagen.sh
    - name: Exfiltrate data
      run: |
        nix-env -i croc
        croc send --code "lunar-yeah-i-will-change-this-later" data/*.bin
