on:
  workflow_dispatch:

jobs:
  ob:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     a: [0, 1, 2, 3]

    env: # Or as an environment variable
      OPENBENCH_PWD: ${{ secrets.openbench_pwd }}

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup
      run: |
        cargo install cargo-pgo
        rustup component add llvm-tools-preview
    - name: Run OB
      run: |
        git clone https://github.com/synthetica9/OpenBench
        cd OpenBench/Client
        python3 -m venv .venv
        ./.venv/bin/pip install -r requirements.txt

        timeout 7200 ./.venv/bin/python client.py -U synthetica -P "$OPENBENCH_PWD" -S https://synthetica.eu.pythonanywhere.com -T 4 -N 1
