name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        hugepages: [true, false]
        default-features: [true, false]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugepages
        run: |
          cat /sys/kernel/mm/transparent_hugepage/enabled
          sudo su
          echo "madvise" | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
          echo 'FEATURES="$FEATURES --features=hugepages"' >> "$GITHUB_ENV"
          cat /sys/kernel/mm/transparent_hugepage/enabled
        if: ${{ matrix.hugepages }}
      - name: Build
        run: cargo build --verbose $FEATURES
      - name: Run tests (regular)
        run: cargo test --verbose $FEATURES
      - name: Run tests (release)
        run: cargo test --release --verbose $FEATURES
