name: Self-Play

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        pgo: ["", "--no-pgo"]
        offset: [1,2,3,4,5,6,7,8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # We also need the previous commit to compare to
        with:
          fetch-depth: 0
      - name: Show git log
        run: |
          git --no-pager show ${{ github.event.after }}
          git --no-pager show ${{ github.event.after }}~${{ matrix.offset }}
      - name: Install PGO deps
        run: |
          cargo install cargo-pgo
          rustup component add llvm-tools-preview
      - name: Run self-play
        run: |
          python ./scripts/selfplay.py ${{ matrix.pgo }} \
             ${{ github.event.after }} ${{ github.event.after }}~${{ matrix.offset }}
      - name: Move artefact
        run: |
          mv out.pgn out_${{ env.RUN_UNIQUE_ID }}_${{ matrix.step }}.pgn
      - name: Publish PGN
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RUN_UNIQUE_ID }}_${{ matrix.step }}_pgn
          path: "*.pgn"
          compression-level: 9
