name: Self-Play

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # We also need the previous commit to compare to
        with:
          fetch-depth: 0
      - name: Run self-play
        run: python ./scripts/selfplay.py ${{ github.event.before }} ${{ github.event.after }}
      - name: Publish PGN
        uses: actions/upload-artifact@v3
        with:
          name: pgn
          path: out.pgn
